import turtle

#'이'자 쓰기
turtle.circle(30)
turtle.penup()
turtle.goto(50, 80)
turtle.pendown()
turtle.right(90)
turtle.forward(100)

#'현'자 쓰기
turtle.penup()
turtle.left(90)
turtle.goto(150, 20)
turtle.pendown()
turtle.circle(20)
turtle.penup()
turtle.goto(120, 70)
turtle.pendown()
turtle.forward(60)
turtle.penup()
turtle.goto(130, 80)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.goto(200, 80)
turtle.pendown()
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.penup()
turtle.goto(180, 55)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.goto(180, 30)
turtle.pendown()
turtle.forward(20)
turtle.penup()
turtle.goto(140, 0)
turtle.pendown()
turtle.right(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(80)

#'우'자 쓰기
turtle.penup()
turtle.goto(300, 40)
turtle.pendown()
turtle.circle(25)
turtle.penup()
turtle.goto(260, 20)
turtle.pendown()
turtle.forward(80)
turtle.penup()
turtle.goto(300, 20)
turtle.pendown()
turtle.right(90)
turtle.forward(40)
turtle.left(90)

# 홈으로
turtle.penup()
turtle.home()
turtle.exitonclick()
